name: Jean-Baptiste Botello
favicon: null
layout_spectrum: 0.7791931603569537
typography_spectrum: 0.2811948175076395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.38322373665869236
  lightness: 0.4606407310348004
  saturation: 0.24131124117411673
  rhythmicContrast: 0.4488386681769043
purpose: []
